general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on || alsactl init
}

listener {
    timeout = 10
    on-timeout = brightnessctl -sd tpacpi::kbd_backlight set 0 || true
    on-resume = brightnessctl -rd tpacpi::kbd_backlight || true
}

listener {
    timeout = 60
    on-timeout = brightnessctl -sd intel_backlight set 10 || true
    on-resume = brightnessctl -rd intel_backlight || true
}

listener {
    timeout = 120
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}