background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 240, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(586e75)
    inner_color = rgb(002b36)
    font_color = rgb(839496)
    fade_on_empty = false
    rounding = 8
    placeholder_text = Password...
    position = 0, -20
    halign = center
    valign = center
}